name: Tata Play IPTV Playlist 5 Daily Workflow
on:
 schedule:
   - cron: "00 11  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Loop
      run: |
            git config --global user.name "$git_id"
            git config --global user.email "$git_mail"
            git clone https://$git_token@github.com/$git_id/Tata-Play-IPTV-Playlist-5-Daily-Generator
            cd Tata-Play-IPTV-Playlist-5-Daily-Generator/           
            cd code_samples/
            curl -s 'https://raw.githubusercontent.com/Mobassar4u/Tata-Play-IPTV-Playlist-Maker/main/dependencies/post_script.exp' > script.exp
            curl -s 'https://raw.githubusercontent.com/Mobassar4u/Tata-Play-IPTV-India/main/code_samples/allChannels.json' > allChannels.json
            chmod 755 *
            sudo apt-get install expect -y
            ./script.exp
            git clone ${gist_url}
            rm ${dir}/TataPlayPlaylist.m3u
            mv *.m3u ${dir}/
            cd ${dir}
            git add .
            git commit -m "Playlist has been updated."
            git push
            exit
